import { callLLM } from './client'
import { playlistMetaPrompt, systemPrompt } from './prompts'
import type { Persona, PlaylistMeta, PlaylistMetaInput } from './types'

export async function generatePlaylistMeta(input: PlaylistMetaInput): Promise<PlaylistMeta> {
  const fallbackName = `${input.persona}_${input.promptName}`.slice(0, 100)

  try {
    const content = await callLLM({
      persona: input.persona,
      messages: [
        { role: 'system', content: systemPrompt(input.persona) },
        { role: 'user', content: playlistMetaPrompt(input) },
      ],
      responseFormat: { type: 'json_object' },
    })

    const parsed = JSON.parse(content) as Partial<PlaylistMeta>
    const name = (parsed.name ?? fallbackName).slice(0, 100)
    const description = parsed.description ?? `Generated by Runway from prompt: ${input.promptName}`

    return { name, description }
  } catch (err) {
    console.error('[LLM] playlist metadata failed, using fallback:', err)
    return {
      name: fallbackName,
      description: `Generated by Runway from prompt: ${input.promptName}`,
    }
  }
}

export function generateDefaultPlaylistMeta(
  persona: Persona,
  promptName: string
): PlaylistMeta {
  return {
    name: `${persona}_${promptName}`.slice(0, 100),
    description: `Generated by Runway from prompt: ${promptName}`,
  }
}
