import { NextResponse, type NextRequest } from 'next/server'
import { createServiceClient, getAuthenticatedUser } from '@/lib/supabase/server'
import {
  searchSpotify,
  searchTidal,
  createSpotifyPlaylist,
  createTidalPlaylist,
  deduplicateTracks,
  type DiscoveredTrack,
} from '@/lib/music'
import { generatePlaylistMeta } from '@/lib/llm'
import type { Prompt, Service } from '@/lib/types'
import type { Persona } from '@/lib/llm'

function buildQuery(prompt: Prompt): string {
  const parts: string[] = []
  if (prompt.label) parts.push(`label:"${prompt.label}"`)
  if (prompt.genre) parts.push(prompt.genre)
  if (prompt.energy) parts.push(prompt.energy)
  if (prompt.bpm_min && prompt.bpm_max) parts.push(`${prompt.bpm_min}-${prompt.bpm_max} bpm`)
  return parts.join(' ') || prompt.name
}

function releaseDateCutoff(range: string | null): string | null {
  const now = new Date()
  switch (range) {
    case 'last_3_months':
      now.setMonth(now.getMonth() - 3)
      break
    case 'last_6_months':
      now.setMonth(now.getMonth() - 6)
      break
    case 'last_year':
      now.setFullYear(now.getFullYear() - 1)
      break
    case 'all':
      return null
    default:
      now.setMonth(now.getMonth() - 3)
  }
  return now.toISOString().slice(0, 10)
}

function filterByReleaseDate(tracks: DiscoveredTrack[], range: string | null): DiscoveredTrack[] {
  const cutoff = releaseDateCutoff(range)
  if (!cutoff) return tracks
  return tracks.filter((t) => {
    if (!t.releaseDate) return false
    return t.releaseDate >= cutoff
  })
}

export async function POST(request: NextRequest) {
  const supabase = await createServiceClient()

  const { user } = await getAuthenticatedUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await request.json().catch(() => null)
  if (!body) return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })

  const { prompt_id, agent = 'CLAUDE', service = 'tidal' } = body as {
    prompt_id?: string
    agent?: string
    service?: Service
  }

  if (!prompt_id) {
    return NextResponse.json({ error: 'prompt_id is required' }, { status: 400 })
  }
  if (!agent || !['KIMI', 'CLAUDE'].includes(agent)) {
    return NextResponse.json({ error: 'agent must be KIMI or CLAUDE' }, { status: 400 })
  }
  if (!service || !['spotify', 'tidal', 'beatport'].includes(service)) {
    return NextResponse.json({ error: 'service must be spotify, tidal, or beatport' }, { status: 400 })
  }

  // Get prompt
  const { data: prompt } = await supabase.from('prompts').select('*').eq('id', prompt_id).single()
  if (!prompt) {
    return NextResponse.json({ error: 'Prompt not found' }, { status: 404 })
  }

  const promptName = (prompt as Prompt).name

  // Create run record
  const { data: run, error: runError } = await supabase
    .from('agent_runs')
    .insert({ agent, prompt_name: promptName, status: 'running', user_id: user.id })
    .select()
    .single()

  if (runError || !run) {
    return NextResponse.json({ error: runError?.message ?? 'Failed to create run' }, { status: 500 })
  }

  try {
    // Get token (not needed for Beatport catalog search, but keep structure consistent)
    const { data: tokenRow } = await supabase
      .from('user_tokens')
      .select('access_token, service_user_id')
      .eq('user_id', user.id)
      .eq('service', service)
      .single()

    let token = tokenRow?.access_token ?? ''
    if (!token && service !== 'beatport') {
      throw new Error(`No ${service} token found. Connect your account in Settings.`)
    }

    const query = buildQuery(prompt as Prompt)
    const limit = (prompt as Prompt).limit ?? 20

    // Search tracks
    let tracks: DiscoveredTrack[] = []
    if (service === 'spotify') {
      tracks = await searchSpotify(token, query, limit)
    } else if (service === 'tidal') {
      tracks = await searchTidal(token, query, limit)
    } else {
      // beatport: search catalog and save tracks to Supabase (no external playlist creation)
      const { searchBeatport } = await import('@/lib/beatport')
      tracks = await searchBeatport(token, query, limit)
    }

    // Enforce prompt release-date filter
    const dateFiltered = filterByReleaseDate(tracks, (prompt as Prompt).release_date_range)
    const uniqueTracks = deduplicateTracks(dateFiltered).slice(0, limit)

    if (uniqueTracks.length === 0) {
      throw new Error(`No ${service} tracks found for query: ${query}`)
    }

    // LLM: generate persona-aligned playlist name and description.
    let playlistName = `${agent}_${promptName}`
    let description = `Generated by Runway from prompt: ${promptName}`
    try {
      const meta = await generatePlaylistMeta({
        persona: agent as Persona,
        promptName,
        genre: (prompt as Prompt).genre,
        energy: (prompt as Prompt).energy,
        bpmMin: (prompt as Prompt).bpm_min,
        bpmMax: (prompt as Prompt).bpm_max,
      })
      playlistName = meta.name
      description = meta.description
    } catch (e) {
      console.error('[RunPrompt] LLM metadata generation failed, using default:', e)
    }

    // Create playlist (skip for beatport — API doesn't support it)
    let created
    if (service === 'beatport') {
      // Beatport has no playlist creation API — create a virtual playlist record in Supabase
      created = {
        name: playlistName,
        id: `beatport-${Date.now()}`,
        track_count: uniqueTracks.length,
        url: null,
      }
    } else if (service === 'spotify') {
      // Need Spotify user id
      const profileRes = await fetch('https://api.spotify.com/v1/me', {
        headers: { Authorization: `Bearer ${token}` },
      })
      if (!profileRes.ok) throw new Error('Failed to fetch Spotify profile')
      const profile = await profileRes.json()
      created = await createSpotifyPlaylist(token, profile.id, playlistName, description, uniqueTracks)
    } else {
      created = await createTidalPlaylist(token, playlistName, description, uniqueTracks)
    }

    // Save playlist to Supabase
    const { data: playlistRecord, error: playlistError } = await supabase
      .from('playlists')
      .insert({
        name: created.name,
        agent,
        service,
        external_id: created.id,
        track_count: created.track_count,
        prompt_name: promptName,
        user_id: user.id,
      })
      .select()
      .single()

    if (playlistError) {
      console.error('[RunPrompt] Failed to save playlist record:', playlistError)
    }

    // Save tracks and link them to the playlist so they appear in the dashboard
    if (playlistRecord) {
      const trackRows = uniqueTracks.map((track) => ({
        title: track.title,
        artist: track.artist,
        album: track.album,
        source: track.source,
        discovered_by: agent,
        discovered_at: new Date().toISOString(),
        prompt_name: promptName,
        playlist_id: playlistRecord.id,
        release_date: track.releaseDate ?? null,
        user_id: user.id,
      }))
      const { error: tracksError } = await supabase.from('tracks').insert(trackRows)
      if (tracksError) {
        console.error('[RunPrompt] Failed to save tracks:', tracksError)
      }
    }

    // Complete run
    await supabase
      .from('agent_runs')
      .update({
        status: 'completed',
        tracks_found: uniqueTracks.length,
        tracks_matched: uniqueTracks.length,
        completed_at: new Date().toISOString(),
      })
      .eq('id', run.id)

    return NextResponse.json({
      run_id: run.id,
      status: 'completed',
      playlist: created,
      saved: !!playlistRecord,
    })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    await supabase
      .from('agent_runs')
      .update({ status: 'failed', completed_at: new Date().toISOString() })
      .eq('id', run.id)
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
